# Generated by Django 5.2.7 on 2025-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_city_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Oczekuje na zatwierdzenie'), ('pending', 'Oczekujące'), ('processing', 'W trakcie realizacji'), ('shipped', 'Wysłane'), ('delivered', 'Dostarczone'), ('canceled', 'Anulowane'), ('rejected', 'Odrzucone')], default='pending_approval', max_length=20),
        ),
    ]
