# Generated by Django 5.2.7 on 2025-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_rejection_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ukryty'),
        ),
    ]
