# Generated by Django 5.2.7 on 2025-11-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden_by_admin',
            field=models.BooleanField(default=False, verbose_name='Ukryty przez administratora'),
        ),
    ]
